### ISSUE TITLE
Same page links

### ISSUE THREAD

**Issue by Jeff17Robbins** [jerriep/copy-markdown-as-html#1]
Github-flavored markdown automatically creates named anchors for each header.

So, for example, this markdown's links work:

```
# Item A
- see [Item B](#item-b)

# Item B 
- see [Item A](#item-a)
```

It would be great if the HTML generated could contain `<a name="foo">` for a given header `foo`.

Right now, the HTML generated is:

```
<h1 id="item-a">Item A</h1>
<ul>
  <li>see <a href="#item-b">Item B</a></li>
</ul>
<h1 id="item-b">Item B</h1>
<ul>
  <li>see <a href="#item-a">Item A</a></li>
</ul>
```

and, of course, those `<a href=...` go nowhere.

**Comment by jerriep** [comment]
@Jeff17Robbins First off, apologies for not responding to this! I did not configure my GH settings to watch this repo, and I completely forgot about it for a long time... 😞

I do not quite understand the issue here. It seems to me the HTML generated is correct. Can you perhaps give an example of the HTML you are expecting it to generate?

**Comment by Jeff17Robbins** [comment]
@jerriep no worries!

My original posting had a markdown error (ironic) and so it was likely unclear.  What I had meant to say was

> It would be great if the HTML generated could contain `<a name="foo">` for a given header `foo`.

Without the named anchor `<a name="foo">`,  the bookmark reference `<a href="#foo">` doesn't work since there's no named anchor for the browser to move to.

The *name* attribute is outdated, and I should have used the *id* attribute, but the intent was that the *href*  anchor in one spot should jump to the corresponding header.

So, for the example markdown

```
# Item A
- see [Item B](#item-b)

# Item B 
- see [Item A](#item-a)
```

I was expecting to see something that functioned like this:

```
<h1 id="item-a">Item A</h1>

- see [Item B](#item-b)

<!-- <br>s added to illustrate jumping better -->
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<h1 id="item-b">Item B</h1>

- see [Item A](#item-a)
```

For some reason, I thought this is how it worked in Github Flavored Markdown.  I think due to postings I had read like [this one](https://stackoverflow.com/questions/27981247/github-markdown-same-page-link).   But in picking up this issue again, I am confused as to what I thought or what actually works in Github.

But, to summarize, I was hoping that same page links would function and jump from the *href* to the *header*.

**Comment by jerriep** [comment]
Currently, I am using the `marked` NPM package for generating the markdown, which is very limited. I will look into replacing it with [markdown-it](https://www.npmjs.com/package/markdown-it) which is what VS Code itself uses for generating HTML previews for markdown. That should provide some better configurability which will hopefully address your issue.

**Comment by jerriep** [comment]
@Jeff17Robbins Yeah, it seems not even GFM does this, so not sure how much I can do about this.

**Comment by Jeff17Robbins** [comment]
Thanks for checking!  And thank you for a useful tool!

**Comment by jerriep** [comment]
OK, if you don't mind I am going to close this one as it is not something which the markdown engines implement
