### ISSUE TITLE
Special char

### ISSUE THREAD

**Issue by yukulele** [jerriep/copy-markdown-as-html#2]
Doesn't works with non ascii char

example: 

`j’ai déjà vu ça`
&darr;
`<p>j‚Äôai d√©j√† vu √ßa</p>`

**Comment by jerriep** [comment]
Wow, apologies for not checking this sooner. I completely forgot about this little extension 😞

Howeber, I cannot reproduce on VS Code 1.21.1 

For

```
j’ai déjà vu ça
```

my output is 

```
<p>j’ai déjà vu ça</p>
```

If you are still interested in this issue after all this time, and you can give me more details to reproduce it, then I will be happy to look into it.

**Comment by jerriep** [comment]
@yukulele I published 1.1.0. This uses new NPM packages for both the markdown conversion and copying the text to the clipboard.

Please try and let me know if this resolves your issue 🤞

**Comment by jerriep** [comment]
Please upgrade to 1.1.0. This should solve the issue as reported in #4
