### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by GoodPotatoe** [jerriep/copy-markdown-as-html#4]
Hey Jerriep

Im have a problem with the copying into html.
Because the text im writing is in german, which mean it contains special characters like äöü.
The thing is, if i copy it into html the ä looks like this <p>√§</p>.
Is there anything I can do to fix this?

**Comment by jerriep** [comment]
Very strange... I took the following text

```
äöü
```

And when I copied it as HTML I get the following:

```
<p>äöü</p>
```

So there seems to be no problems for me.

This was reported before in #2 and in that case I could also not reproduce.

Can you please share some more information with me:

1. What version of VS Code are you using?
2. What operating system (OS) and version are you using?
3. What is the current input language for your OS?

**Comment by GoodPotatoe** [comment]
What version of VS Code are you using?
Version 1.21.1 (1.21.1)

What operating system (OS) and version are you using?
Mac OS High Sierra 10.13.3

What is the current input language for your OS?
German Swiss

**Comment by jerriep** [comment]
@GoodPotatoe I am a bit dumbfounded by this one. I configured my Mac with the Swiss German keyboard and typed some German characters into a markdown document. I then used the extension to copy the markdown as HTML to the clipboard, but still it worked fine for me.

In any case, I plan to upgrade to a new markdown parser in the extension, so let me do that and maybe that fixes the problem...

**Comment by GoodPotatoe** [comment]
@jerriep alright, will you inform when the new update is up?

**Comment by jerriep** [comment]
@GoodPotatoe I published 1.1.0. This uses new NPM packages for both the markdown conversion and copying the text to the clipboard. 

Please try and let me know if this resolves your issue 🤞

**Comment by GoodPotatoe** [comment]
@jerriep Thanks! now it works :)

**Comment by jerriep** [comment]
Excellent! :D
