### ISSUE TITLE
copy window content as rich text/html

### ISSUE THREAD

**Issue by hellboy81** [jerriep/copy-markdown-as-html#5]
Plugin needed to make available to copy VS Code editor content preserving syntax highlighting (also compatible with pasting in Word/Outlook)

**Comment by jerriep** [comment]
This plugin is for markdown which does not contain syntax highlighting, so I am not sure I understand what you mean.

Are you referring to code blocks inside a markdown document?

A better explanation will be helpful - perhaps with a screenshot of what it is you are talking about?

**Comment by jerriep** [comment]
@hellboy81 I am closing this since you are unable to provide clarification. Feel free to re-open if you are willing to provide more information.
